# Generated by Django 2.2.24 on 2021-06-29 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_tel', models.CharField(max_length=13)),
                ('numero_de_chambre', models.CharField(max_length=3)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin'), ('A', 'Autre')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
