# Generated by Django 2.0.7 on 2021-06-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='take_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=12)),
                ('numero_de_telephone', models.CharField(max_length=13)),
                ('numero_de_chambre', models.CharField(max_length=3)),
                ('date_de_trouvaille', models.DateTimeField()),
                ('description', models.TextField()),
                ('objet', models.ForeignKey(default=None, on_delete=False, to='objects.objetPerdu')),
            ],
        ),
    ]
