# Generated by Django 2.0.7 on 2021-06-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='take_form',
            old_name='date_de_trouvaille',
            new_name='date_de_perte',
        ),
    ]
