# Generated by Django 2.0.7 on 2021-07-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_form', '0002_auto_20210627_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='take_form',
            name='objet',
        ),
        migrations.AddField(
            model_name='take_form',
            name='objet_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='take_form',
            name='date_de_perte',
            field=models.DateField(),
        ),
    ]
