# Generated by Django 2.0.7 on 2021-07-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_form', '0003_auto_20210705_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take_form',
            name='objet_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
