# Generated by Django 2.0.7 on 2021-07-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20210704_0202'),
        ('take_form', '0006_auto_20210705_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='take_form',
            name='objet_id',
        ),
        migrations.AddField(
            model_name='take_form',
            name='objet',
            field=models.ForeignKey(default=None, on_delete=False, to='objects.objetPerdu'),
        ),
    ]
